In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Init: Information and Cleaning Data

In [10]:
#--Read the file and see some data:
file = '/kaggle/input/videogamesales/vgsales.csv'
df = pd.read_csv(file)
df.head(3)
#--Show data from certain Row number:
# df.loc[170:180]

In [3]:
#--Check info (Type data, tot Row n Col) from data file:
df.info()

In [4]:
#--Check if there's null data:
df.isnull().sum()

In [6]:
#--Check Detail data which having null value:
dt_null_year = pd.isnull(df['Year'])
df[dt_null_year].head(3)

In [18]:
#--Make a Function to Check Detail data which having null value:
def check_detail_null(column):
    dt_null = pd.isnull(df[column])
    return df[dt_null].head(3)

check_detail_null('Publisher')

In [17]:
#--Handling Null value:
#1. Ignore or Drop if it's not really important
#2. Fill with 0 or Mean Value
#3. Filling a missing value with previous ones. 'df.fillna(method ='pad')'
#4. Filling null value with the next ones. 'df.fillna(method ='bfill')'
#5. Replace the all Nan value in the data frame with -99 value. 'df.replace(to_replace = np.nan, value = -99)' 
#6. Drop a Rows whose having NULL. 'df.dropna(how = 'all')'
#7. Drop a Columns whose having NULL. 'df.dropna(axis = 1)'

##--NOTES--##
# if df.fillna____ => mean FILL ALL NULL VALUE
# if df['Column Name'].fillna___ => mean FILL ONLY at That Column

df.fillna(method ='pad', inplace=True)
df.loc[170:190]

In [ ]:
#--Change datatype if it's required:

# Process: Start the Analysis

In [ ]:
#--Start Mission