In [5]:
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('NumberofGraduatesinHigherEducation2012-2019.csv')
df.head()

,Academic_Year,Institution_Type_EN,Institution_Type_AR,Campus_Zone_EN,Campus_Zone_AR,Coordinates,LocalFlag_EN,LocalFlag_AR,Gender_EN,Gender_AR,Bachelors,Certificate,Diploma,Doctorate,Graduate Certificate,Graduate Diploma,Higher Diploma,Masters,Other أخرى,Total
0,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Expat,غير مواطن,Female,انثى,235,NaN,NaN,NaN,NaN,NaN,NaN,40,NaN,275
1,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Expat,غير مواطن,Male,ذكر,126,NaN,10.0,NaN,NaN,NaN,1.0,42,NaN,179
2,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Local,مواطن,Female,انثى,"1,838",5.0,532.0,NaN,NaN,NaN,192.0,280,NaN,"2,847"
3,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Local,مواطن,Male,ذكر,886,54.0,229.0,NaN,NaN,NaN,193.0,185,NaN,"1,547"
4,2012-2013,Federal,اتحادية,Dubai,دبي,"25.276987 , 55.296249",Expat,غير مواطن,Female,انثى,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

## 1.1. Question: What is the average number of students enrolled in the Bachelor's program across all campuses and institution types for the 2012-2013 academic year?

In [ ]:
# Calculate the average number of students enrolled in Bachelor's programs for the entire dataset
average_bachelors = df['Bachelors'].mean()

print(f"The average number of students enrolled in the Bachelor's program across all campuses and institution types: {average_bachelors:.2f}")

## 1.2. Question: What is the total number of students enrolled in Master's programs by institution type (Federal vs Non-Federal) in the 2012-2013 academic year?

In [ ]:
# Group by Institution Type and sum the number of students enrolled in Master's programs
masters_by_institution_type = df.groupby('Institution_Type_EN')['Masters'].sum()

print("Total number of students enrolled in Master's programs by institution type:")
print(masters_by_institution_type)

## 1.3. Question: What is the gender distribution for students enrolled in Graduate Certificate programs across all campuses ?

In [ ]:
# Group by Gender and sum the number of students enrolled in Graduate Certificate programs
gender_distribution_graduate_cert = df.groupby('Gender_EN')['Graduate Certificate'].sum()

print("Gender distribution for students enrolled in Graduate Certificate programs:")
print(gender_distribution_graduate_cert)

## 3.1. Question: How many female students are enrolled in Federal institutions in Abu Dhabi for the 2012-2013 academic year who are pursuing a Bachelor's degree?

In [3]:
# Filter the data based on multiple conditions:
# - Institution Type: 'Federal'
# - Campus Zone: 'Abu Dhabi'
# - Gender: 'Female'
# - Bachelor's Degree (non-null or greater than 0)
# female_bachelors_abudhabi_federal = df[
#     (df['Institution_Type_EN'] == 'Federal') &
#     (df['Campus_Zone_EN'] == 'Abu Dhabi') &
#     (df['Gender_EN'] == 'Female') &
#     (df['Bachelors'] > 0)
# ]

# Count the number of female students in the filtered data
# female_bachelors_abudhabi_federal_count = female_bachelors_abudhabi_federal.shape[0]

# print(f"Number of female students enrolled in Bachelor's program at Federal institutions in Abu Dhabi: {female_bachelors_abudhabi_federal_count}")

df.head()

,Academic_Year,Institution_Type_EN,Institution_Type_AR,Campus_Zone_EN,Campus_Zone_AR,Coordinates,LocalFlag_EN,LocalFlag_AR,Gender_EN,Gender_AR,Bachelors,Certificate,Diploma,Doctorate,Graduate Certificate,Graduate Diploma,Higher Diploma,Masters,Other أخرى,Total
0,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Expat,غير مواطن,Female,انثى,235,NaN,NaN,NaN,NaN,NaN,NaN,40,NaN,275
1,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Expat,غير مواطن,Male,ذكر,126,NaN,10.0,NaN,NaN,NaN,1.0,42,NaN,179
2,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Local,مواطن,Female,انثى,"1,838",5.0,532.0,NaN,NaN,NaN,192.0,280,NaN,"2,847"
3,2012-2013,Federal,اتحادية,Abu Dhabi,أبوظبي,"24.466667 , 54.366669",Local,مواطن,Male,ذكر,886,54.0,229.0,NaN,NaN,NaN,193.0,185,NaN,"1,547"
4,2012-2013,Federal,اتحادية,Dubai,دبي,"25.276987 , 55.296249",Expat,غير مواطن,Female,انثى,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

## 3.2. Question: How many male students from Expat status are enrolled in Master's programs in any institution in Dubai for the 2012-2013 academic year?

In [ ]:
# Filter the data for Expat status, Male gender, and Master's program in Dubai
male_expat_masters_dubai = df[
    (df['LocalFlag_EN'] == 'Expat') &
    (df['Gender_EN'] == 'Male') &
    (df['Masters'] > 0) &
    (df['Campus_Zone_EN'] == 'Dubai')
]

# Count the number of male expat students enrolled in Master's programs
male_expat_masters_dubai_count = male_expat_masters_dubai.shape[0]

print(f"Number of male expatriates enrolled in Master's programs at institutions in Dubai: {male_expat_masters_dubai_count}")

## 3.3. Question: How many local students in Sharjah are enrolled in any kind of graduate-level program (Graduate Certificate, Graduate Diploma, or Higher Diploma) for the 2012-2013 academic year?

In [ ]:
# Filter the data for local students in Sharjah with graduate-level programs
local_graduate_sharjah = df[
    (df['LocalFlag_EN'] == 'Local') &
    (df['Campus_Zone_EN'] == 'Sharjah') &
    (
        (df['Graduate Certificate'] > 0) | 
        (df['Graduate Diploma'] > 0) | 
        (df['Higher Diploma'] > 0)
    )
]

# Count the number of local students enrolled in graduate programs in Sharjah
local_graduate_sharjah_count = local_graduate_sharjah.shape[0]

print(f"Number of local students enrolled in graduate programs at institutions in Sharjah: {local_graduate_sharjah_count}")

## 4.1. Question: What is the total number of students enrolled in all programs (Bachelor's, Master's, etc.) by Campus Zone for the 2012-2013 academic year?
This question will allow you to see the total number of students enrolled in various programs for each campus zone.

In [ ]:
# Group the data by 'Campus_Zone_EN' and sum all the columns that represent student counts
total_students_by_zone = df.groupby('Campus_Zone_EN').sum()

# Since the dataset has many columns, we may want to focus only on the student enrollment columns
student_columns = ['Bachelors', 'Certificate', 'Diploma', 'Doctorate', 'Graduate Certificate', 
                   'Graduate Diploma', 'Higher Diploma', 'Masters', 'Other ÿ£ÿÆÿ±Ÿâ']
total_students_by_zone = total_students_by_zone[student_columns]

# Show the total number of students enrolled in all programs by campus zone
print("Total number of students enrolled in all programs by campus zone:")
print(total_students_by_zone)

## 4.2.  Question: What is the average number of students enrolled in Graduate Diploma programs by Institution Type for the 2012-2013 academic year?
This question helps you understand the average enrollment in the Graduate Diploma program across different types of institutions (Federal vs Non-Federal).

In [ ]:
# Group the data by 'Institution_Type_EN' and calculate the mean for 'Graduate Diploma' program
average_grad_diploma_by_type = data.groupby('Institution_Type_EN')['Graduate Diploma'].mean()

print("Average number of students enrolled in Graduate Diploma programs by institution type:")
print(average_grad_diploma_by_type)

## 5.1. Question: Sort by "Total" in Descending Order to Find the Campus with the Highest Number of Students

In [ ]:
# Sort the dataset by the "Total" column in descending order
sorted_total_desc = df.sort_values(by="Total", ascending=False)

# Display the campus with the highest number of students
highest_total_campus = sorted_total_desc.iloc[0]  # First row
print("Campus with the highest total number of students:")
print(highest_total_campus)

## 5.2. Sort by "Bachelors" in Ascending Order to Find the Five Campuses with the Fewest Bachelor Students

In [ ]:
# Sort the dataset by the "Bachelors" column in ascending order
sorted_bachelors_asc = df.sort_values(by="Bachelors", ascending=True)

# Display the top five rows with the fewest bachelor students
lowest_bachelor_campuses = sorted_bachelors_asc.head(5)
print("Five campuses with the lowest number of bachelor students:")
print(lowest_bachelor_campuses)

## 6.1. Which gender (Male/Female) had the highest total number of students across all campuses? Use grouping and sorting to find the answer.

In [ ]:
# Group by 'Gender_EN' and calculate the total students for each gender
gender_totals = df.groupby('Gender_EN')['Total'].sum()

# Sort the results in descending order
gender_totals_sorted = gender_totals.sort_values(ascending=False)

# Display the gender with the highest total
print("Gender with the highest total number of students:")
print(gender_totals_sorted)

## 6.2. What is the total number of local students (LocalFlag_EN = "Local") for each campus, and which campus has the highest number? Filter, group, and sort the data.

In [ ]:
# Filter for local students
local_students = df[df['LocalFlag_EN'] == 'Local']

# Group by 'Campus_Zone_EN' and calculate the total for each campus
local_totals = local_students.groupby('Campus_Zone_EN')['Total'].sum()

# Sort the results in descending order
local_totals_sorted = local_totals.sort_values(ascending=False)

# Display the campus with the highest number of local students
print("Campus with the highest number of local students:")
print(local_totals_sorted)

## 7.1. What is the distribution of the total number of students across different campuses?

In [ ]:
# Group the data by 'Campus_Zone_EN' and sum the 'Total' column
campus_totals = df.groupby('Campus_Zone_EN')['Total'].sum()

# Plot a bar chart
plt.figure(figsize=(10, 6))
campus_totals.sort_values(ascending=False).plot(kind='bar', color='skyblue')

# Add chart title and labels
plt.title('Total Number of Students by Campus', fontsize=14)
plt.xlabel('Campus', fontsize=12)
plt.ylabel('Total Students', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(['Total Students'], loc='upper right')
plt.tight_layout()

# Display the chart
plt.show()

## 7.2. What is the gender-wise breakdown of total students?

In [ ]:
# Group the data by 'Gender_EN' and sum the 'Total' column
gender_totals = df.groupby('Gender_EN')['Total'].sum()

# Plot a pie chart
plt.figure(figsize=(8, 8))
gender_totals.plot(kind='pie', autopct='%1.1f%%', startangle=140, colors=['lightcoral', 'skyblue'])

# Add chart title
plt.title('Gender-wise Distribution of Total Students', fontsize=14)
plt.ylabel('')  # Remove y-axis label for better aesthetics
plt.legend(gender_totals.index, loc='upper right')

# Display the chart
plt.show()

## 7.3. Visualizing Trends in Number of Graduates Over Time

Description of the Visualization:
X-Axis: Represents the Academic_Year to show the time period.
Y-Axis: Represents the total number of graduates across all graduate categories.
Line Chart: Shows how the number of graduates changes over time, helping to identify upward or downward trends.

In [ ]:
# Group the data by 'Academic_Year' and calculate the sum of graduate-related columns
graduate_columns = ['Bachelors', 'Certificate', 'Diploma', 'Doctorate', 
                    'Graduate Certificate', 'Graduate Diploma', 'Higher Diploma', 'Masters']

# Sum all graduate-related columns for each year
graduates_over_time = df.groupby('Academic_Year')[graduate_columns].sum()

# Calculate the total graduates for each year
graduates_over_time['Total Graduates'] = graduates_over_time.sum(axis=1)

# Plot the trend of total graduates over time
plt.figure(figsize=(10, 6))
plt.plot(graduates_over_time.index, graduates_over_time['Total Graduates'], marker='o', color='teal', linewidth=2)

# Add chart title and labels
plt.title('Trends in the Number of Graduates Over Time', fontsize=14)
plt.xlabel('Academic Year', fontsize=12)
plt.ylabel('Total Graduates', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.xticks(rotation=45)

# Display the chart
plt.tight_layout()
plt.show()

In [ ]:
# If you want to break it down by degree type (e.g., Bachelors, Masters), you can plot multiple lines:
# Plot trends for each degree type
plt.figure(figsize=(10, 6))
for column in graduate_columns:
    plt.plot(graduates_over_time.index, graduates_over_time[column], marker='o', label=column)

# Add chart title and labels
plt.title('Trends in Graduates by Degree Type Over Time', fontsize=14)
plt.xlabel('Academic Year', fontsize=12)
plt.ylabel('Number of Graduates', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title='Degree Type')
plt.xticks(rotation=45)

# Display the chart
plt.tight_layout()
plt.show()

# Insights You Can Derive:
# Identify which degree type shows the most consistent growth.
# Spot significant increases or decreases for specific years.
# Compare the trends for different degree types.

## 7.4. Visualizing Trends in Number of Graduates Over Time

In [ ]:
# Group the data by 'Academic_Year' and sum the graduate-related columns
graduate_trends = df.groupby('Academic_Year')[['Bachelors', 'Masters', 'Doctorate']].sum()

# Plot the trends for each graduate type
plt.figure(figsize=(12, 6))
for column in graduate_trends.columns:
    plt.plot(graduate_trends.index, graduate_trends[column], marker='o', label=column)

# Add chart title and labels
plt.title('Trends in the Number of Graduates Over Time', fontsize=16)
plt.xlabel('Academic Year', fontsize=12)
plt.ylabel('Number of Graduates', fontsize=12)
plt.xticks(rotation=45)
plt.legend(title='Graduate Type', fontsize=10)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()

# Display the chart
plt.show()

# Explanation of Code:
# Data Grouping:
#   We group the dataset by Academic_Year to calculate the total number of graduates for each year.
#   Columns like Bachelors, Masters, and Doctorate are summed to observe trends.
# Line Plot:
#   A separate line is plotted for each graduate type (Bachelors, Masters, Doctorate) using plt.plot().
# Visualization Features:
#   The marker='o' parameter highlights each data point.
#   Labels, gridlines, and legends make the chart easier to read.

### Summary Insights from the DataFrame
Based on the provided dataset and its structure, here are some potential insights and recommendations:

1. Gender Distribution
    - Insight: From the grouped data, we can analyze the proportion of male and female students across various campuses and academic years. If one gender consistently dominates certain campuses or programs, it could indicate gender-based preferences or imbalances.

#### Recommendation:
    - Introduce targeted outreach programs or scholarships for underrepresented genders at specific campuses or within programs to promote inclusivity.
    - Justification: A balanced gender ratio encourages diversity and fosters a more inclusive learning environment.

2. Local vs. Expatriate Trends  
    - Insight: The dataset can reveal the ratio of local to expatriate students at different campuses and programs. If expatriates are concentrated in certain locations or programs, it might highlight accessibility or program-specific preferences.

#### Recommendation:
    - Increase marketing efforts or adapt curricula to cater to expatriates at campuses with low expat representation.
        For locals, ensure that campus facilities and programs are tailored to community needs, particularly in regions with a high concentration of local students.
    - Justification: Meeting the specific needs of locals and expatriates can enhance enrollment and satisfaction rates. 

3. Campus-Specific Enrollment
Insight: By analyzing total student enrollment at each campus, it's possible to identify campuses with significantly higher or lower student populations.
Recommendation:

For underperforming campuses, investigate potential barriers to enrollment (e.g., geographic accessibility, program availability) and address them.
Expand capacity or offer new programs at campuses with high demand to accommodate growth.
Justification: Optimizing campus performance ensures resources are allocated effectively and enhances student accessibility.
4. Degree-Specific Trends
Insight: Programs such as Bachelors, Masters, and Diplomas may show different growth patterns over academic years. Bachelors programs typically have the largest enrollment, but post-graduate programs may show growth potential.
Recommendation:

Invest in expanding post-graduate offerings, such as Master's and Doctorate programs, at campuses with growing demand.
Justification: Post-graduate education appeals to working professionals and is critical for institutional prestige and competitiveness.
5. Yearly Trends in Graduate Numbers
Insight: Analyzing graduate trends over time can highlight periods of growth or stagnation in specific programs or campuses.
Recommendation:

For years with low graduation rates, investigate potential factors like program duration, student retention, or academic difficulties. Implement academic support or mentorship programs to address these issues.
Justification: Improving student retention and graduation rates enhances institutional reputation and contributes to long-term sustainability.
6. Popular and Underutilized Programs
Insight: Certain programs (e.g., Bachelors or specific certifications) might consistently have higher enrollments. Conversely, some programs may see consistently low participation.
Recommendation:

For underutilized programs, redesign curricula or align them with job market demands. Promote these programs through targeted marketing campaigns.
Justification: Addressing low enrollment programs ensures resource optimization and relevance to industry trends.
7. Regional Accessibility
Insight: Geographic distribution of campuses and their corresponding enrollments can indicate whether certain regions are underserved.
Recommendation:

Establish new campuses or satellite programs in underserved areas with potential student demand.
Justification: Expanding geographic accessibility increases enrollment opportunities for remote or underserved communities.
General Recommendations for Improvement
Focus on Program Diversification: Expand programs in high-demand fields like technology, healthcare, and business to attract more students.
Improve Data Monitoring: Leverage the current data framework to monitor trends in real-time and adapt strategies accordingly.
Encourage Research and Development: Promote research-oriented Doctorate programs to elevate institutional reputation and attract international students.
By implementing these recommendations, the institution can ensure sustainable growth, better serve its student population, and adapt to changing market demands.